﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace Freshheads.SmartRoom.iOS
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedISmartRoomApi : ISmartRoomApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedISmartRoomApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<ApiResult> UserEnterRoom(int userId,int roomId)
        {
            var arguments = new object[] { userId,roomId };
            return (Task<ApiResult>) methodImpls["UserEnterRoom"](Client, arguments);
        }

        public virtual Task<ApiResult> UserLeftRoom(int userId,int roomId)
        {
            var arguments = new object[] { userId,roomId };
            return (Task<ApiResult>) methodImpls["UserLeftRoom"](Client, arguments);
        }

        public virtual Task<ApiResult> ToggleLight(int lightId,int switchValue,string color)
        {
            var arguments = new object[] { lightId,switchValue,color };
            return (Task<ApiResult>) methodImpls["ToggleLight"](Client, arguments);
        }

    }
}


